apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      securityContext:
        fsGroup: 1000690000
      containers:
      - name: ollama
        image: ollama/ollama:latest
        ports:
        - containerPort: 11434
        env:
        - name: HOME
          value: "/opt/ollama"
        - name: OLLAMA_MODELS
          value: "/opt/ollama/models"
        volumeMounts:
        - name: ollama-storage
          mountPath: /opt/ollama
      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: ollama-data
      nodeSelector:
        gpu-node: "true"
      tolerations:
      - key: "gpu-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      securityContext:
        fsGroup: 1000690000
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service:11434"
        - name: WEBUI_SECRET_KEY
          value: "your_secret_key"
        - name: HOME
          value: "/app/backend/data"
        volumeMounts:
        - name: open-webui-storage
          mountPath: /app/backend/data
      volumes:
      - name: open-webui-storage
        persistentVolumeClaim:
          claimName: open-webui-data
      nodeSelector:
        gpu-node: "true"
      tolerations:
      - key: "gpu-node"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"