apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  labels:
    app: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama-service:11434"
        - name: WEBUI_SECRET_KEY
          value: "your_secret_key"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: open-webui-storage
          mountPath: /app/backend/data
      volumes:
      - name: open-webui-storage
        persistentVolumeClaim:
          claimName: open-webui-data
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: open-webui
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: open-webui-route
spec:
  to:
    kind: Service
    name: open-webui-service
  port:
    targetPort: 8080